Furniture-Management-MVC/Models/Furniture.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Furniture_Management_MVC.Models
{
    public class Furniture
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        public string ItemName { get; set; }

        [Required]
        public string ItemDescription { get; set; }

        [Required]
        public string WoodType { get; set; }

        [Required]
        public double ItemPrice{ get; set; }


        public int CategoryId { get; set; }

        [ForeignKey("CategoryId")]
        public Category Category { get; set; }

        public string CreatedBy { get; set; }

        public DateTime CreatedDate { get; set; }

    }
}

Furniture-Management-MVC/ViewModels/Furniture/AddFurnitureViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Furniture_Management_MVC.ViewModels.Furniture
{
    public class AddFurnitureViewModel
    {
        [Required(ErrorMessage = "Item Name is Mandatory")]
        public string ItemName { get; set; }

        [Required(ErrorMessage = "Item Description is Mandatory")]
        public string ItemDescription { get; set; }

        [Required(ErrorMessage = "Wood Type is Mandatory")]
        public string WoodType { get; set; }

        [Required(ErrorMessage = "Item Price is Mandatory")]
        public double ItemPrice { get; set; }

        [Required(ErrorMessage = "Category is Mandatory")]
        public int CategoryId { get; set; }

        public List<SelectListItem> CategoryList { get; set; }

    }
}

Furniture-Management-MVC/ViewModels/Furniture/DeleteFurnitureViewModel.cs
namespace Furniture_Management_MVC.ViewModels.Furniture
{
    public class DeleteFurnitureViewModel : FurnitureDetailsViewModel
    {
    }
}

Furniture-Management-MVC/ViewModels/Furniture/FurnitureDetailsViewModel.cs
using System;

namespace Furniture_Management_MVC.ViewModels.Furniture
{
    public class FurnitureDetailsViewModel
    {
        public int Id { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public string WoodType { get; set; }

        public double ItemPrice { get; set; }
        public string CategoryName { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }

    }
}

Furniture-Management-MVC/ViewModels/Furniture/UpdateFurnitureViewModel.cs
namespace Furniture_Management_MVC.ViewModels.Furniture
{
    public class UpdateFurnitureViewModel : AddFurnitureViewModel
    {
        public int Id { get; set; }
    }
}

Furniture-Management-MVC/Controllers/FurnitureController.cs
using Furniture_Management_MVC.Models;
using Furniture_Management_MVC.Repository;
using Furniture_Management_MVC.ViewModels.Furniture;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Furniture_Management_MVC.Controllers
{
    [Authorize]
    public class FurnitureController : Controller
    {
        IFurnitureRepository _furnitureRepository;
        ICategoryRepository _categoryRepository;
        public FurnitureController(IFurnitureRepository furnitureRepository, ICategoryRepository categoryRepository)
        {
            _furnitureRepository = furnitureRepository;
            _categoryRepository = categoryRepository;
        }
        public IActionResult Index()
        {
            var furnitures = _furnitureRepository.GetAllFurnitures(User.Identity.Name);

            List<FurnitureDetailsViewModel> furnitureDetailsListViewModel = new List<FurnitureDetailsViewModel>();

            foreach (var furniture in furnitures)
            {
                FurnitureDetailsViewModel furnitureDetailsViewModel = new FurnitureDetailsViewModel
                {
                    Id = furniture.Id,
                    ItemName = furniture.ItemName,
                    ItemDescription = furniture.ItemDescription,
                    WoodType = furniture.WoodType,
                    ItemPrice = furniture.ItemPrice,
                    CategoryName = furniture.Category.CategoryName,
                    CreatedBy = furniture.CreatedBy,
                    CreatedDate = furniture.CreatedDate

                };
                furnitureDetailsListViewModel.Add(furnitureDetailsViewModel);
            }

            return View(furnitureDetailsListViewModel);

        }
        [HttpGet]
        public IActionResult AddFurniture()
        {
            var addFurnitureViewModel = new AddFurnitureViewModel();


            var categories = _categoryRepository.GetAllCategories();
            List<SelectListItem> categorySelectListItems = new List<SelectListItem>();


            foreach (var catg in categories)
            {

                categorySelectListItems.Add(new SelectListItem { Text = catg.CategoryName, Value = catg.CategoryId.ToString() });
            }


            categorySelectListItems.Insert(0, new SelectListItem { Text = "--Select-Category", Value = string.Empty });


            addFurnitureViewModel.CategoryList = categorySelectListItems;

            return View(addFurnitureViewModel);
        }
        [HttpPost]
        public IActionResult AddFurniture(AddFurnitureViewModel furnitureViewModel)
        {
            var addFurnitureViewModel = new AddFurnitureViewModel();


            var categories = _categoryRepository.GetAllCategories();
            List<SelectListItem> categorySelectListItems = new List<SelectListItem>();


            foreach (var catg in categories)
            {

                categorySelectListItems.Add(new SelectListItem { Text = catg.CategoryName, Value = catg.CategoryId.ToString() });
            }


            categorySelectListItems.Insert(0, new SelectListItem { Text = "--Select-Category", Value = string.Empty });


            addFurnitureViewModel.CategoryList = categorySelectListItems;
            if (ModelState.IsValid)
            {
                var existingFurnitures = _furnitureRepository.GetAllFurnitures(User.Identity.Name);
                var furnitures = existingFurnitures?.FirstOrDefault(i => i.ItemName.ToLower() == furnitureViewModel.ItemName.ToLower() && i.WoodType.ToLower() == furnitureViewModel.WoodType.ToLower());
                if (furnitures != null)
                {
                    ModelState.AddModelError("", $"{furnitureViewModel.ItemName} already exists!");
                    return View(addFurnitureViewModel);
                }
                else
                {
                    Furniture furniture = new Furniture
                    {
                        ItemName = furnitureViewModel.ItemName,
                        ItemDescription = furnitureViewModel.ItemDescription,
                        WoodType = furnitureViewModel.WoodType,
                        ItemPrice = furnitureViewModel.ItemPrice,
                        CategoryId = furnitureViewModel.CategoryId,
                        CreatedBy = HttpContext.User.Identity.Name,
                        CreatedDate = DateTime.Now
                    };
                    var addedFurniture = _furnitureRepository.AddFurniture(furniture);
                    return RedirectToAction("Index");
                }
            }
            return View(furnitureViewModel);
        }

       [HttpGet]
        public IActionResult UpdateFurniture(int id)
        {
            var updateFurnitureViewModel = new UpdateFurnitureViewModel();
            var furnitureToBeEdited = _furnitureRepository.GetFurnitureById(id);

           var categories = _categoryRepository.GetAllCategories();
            List<SelectListItem> categorySelectListItems = new List<SelectListItem>();
            foreach (var catg in categories)
            {
                categorySelectListItems.Add(new SelectListItem { Text = catg.CategoryName, Value = catg.CategoryId.ToString() });
            }
            categorySelectListItems.Insert(0, new SelectListItem { Text = "--Select-Category", Value = string.Empty });
            updateFurnitureViewModel.CategoryList = categorySelectListItems;




            updateFurnitureViewModel.Id = furnitureToBeEdited.Id;
            updateFurnitureViewModel.ItemName = furnitureToBeEdited.ItemName;
            updateFurnitureViewModel.ItemDescription = furnitureToBeEdited.ItemDescription;
            updateFurnitureViewModel.WoodType = furnitureToBeEdited.WoodType;
            updateFurnitureViewModel.ItemPrice = furnitureToBeEdited.ItemPrice;
            updateFurnitureViewModel.CategoryId = furnitureToBeEdited.CategoryId;


            return View(updateFurnitureViewModel);

        }
        [HttpPost]
        public IActionResult UpdateFurniture(int id, UpdateFurnitureViewModel updateFurnitureViewModel)
        {
            if (ModelState.IsValid)
            {
                Furniture furniture = new Furniture
                {
                    ItemName = updateFurnitureViewModel.ItemName,
                    ItemDescription = updateFurnitureViewModel.ItemDescription,
                    WoodType = updateFurnitureViewModel.WoodType,
                    ItemPrice = updateFurnitureViewModel.ItemPrice,
                    CategoryId = updateFurnitureViewModel.CategoryId
                };
                _furnitureRepository.UpdateFurniture(id, furniture);
                return RedirectToAction("Index");
            }
            return View(updateFurnitureViewModel);
        }
        [HttpGet]
        public IActionResult DeleteFurniture(int id)
        {
            var furnitureToBeDeleted = _furnitureRepository.GetFullFurnitureDetailsById(id);
            var deleteFurnitureViewModel = new DeleteFurnitureViewModel
            {
                Id = furnitureToBeDeleted.Id,
                ItemName = furnitureToBeDeleted.ItemName,
                ItemDescription = furnitureToBeDeleted.ItemDescription,
                WoodType = furnitureToBeDeleted.WoodType,
                ItemPrice= furnitureToBeDeleted.ItemPrice,
                CategoryName = furnitureToBeDeleted.Category.CategoryName
            };
            return View(deleteFurnitureViewModel);
        }
        [HttpPost]
        public IActionResult DeleteFurniture(DeleteFurnitureViewModel deleteFurnitureViewModel)
        {
            _furnitureRepository.RemoveFurniture(deleteFurnitureViewModel.Id);
            return RedirectToAction("Index");
        }


    }
}

Furniture-Management-MVC/Views/Furniture/AddFurniture.cshtml
@model AddFurnitureViewModel

<link href="~/css/Add.css" rel="stylesheet" />

<h1>Add Furniture</h1>
<hr />

<body style="background-color: #D3D3D3">
<form asp-action="AddFurniture" asp-controller="Furniture" method="post">
<div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">


        <label>Name</label>
        <input type="text" asp-for="ItemName" class="form-control" />
        <span asp-validation-for="ItemName" class="text-danger"></span>

    </div>
    <div class="form-group">
        <label>Category</label>
        <select class="form-control" asp-for="CategoryId" asp-items="@Model.CategoryList"></select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label> Wood Type </label>
        <input type="text" asp-for="WoodType" class="form-control" />
        <span asp-validation-for="WoodType" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Description</label>
        <input type="text" asp-for="ItemDescription" class="form-control" />
        <span asp-validation-for="ItemDescription" class="text-danger"></span>
    </div>
    
    <div class="form-group">
        <label> Price </label>
        <input type="number" asp-for="ItemPrice" class="form-control" />
        <span asp-validation-for="ItemPrice" class="text-danger"></span>
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
     <a class="btn btn-primary" asp-controller="Furniture" asp-action="Index">Cancel</a>
</form>
</body>

Furniture-Management-MVC/Views/Furniture/DeleteFurniture.cshtml
@model DeleteFurnitureViewModel

 
<h2>Do you want to delete the Furniture?</h2>
<hr />
<body style="background-color: #D3D3D3"> 
<form asp-controller="Furniture" asp-action="DeleteFurniture" method="post">
    <div class="row">
        <div class="col-sm-3">
            <label>Name</label>
        </div>
        <div class="col-sm-3">
            @Model.ItemName
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3">
            <label>Category Name</label>
        </div>
        <div class="col-sm-3">
            @Model.CategoryName
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3">
            <label>Wood Type</label>
        </div>
        <div class="col-sm-3">
            @Model.WoodType
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3">
            <label>Description</label>
        </div>
        <div class="col-sm-3">
            @Model.ItemDescription
        </div>
    </div>
    
    <div class="row">
        <div class="col-sm-3">
            <label>Price</label>
        </div>
        <div class="col-sm-3">
            @Model.ItemPrice
        </div>
    </div>
    
    <div class="row">
        <div class="col-sm-12">
            <button type="submit" class="btn btn-danger">Delete</button>
            <a class="btn btn-primary" asp-controller="Furniture" asp-action="Index">Cancel</a>

        </div>

    </div>
</form>
</body>

Furniture-Management-MVC/Views/Furniture/Index.cshtml
@model IEnumerable<FurnitureDetailsViewModel>

<link href="~/css/Index.css" rel="stylesheet" />
<h1 style="text-align:center">Furniture List</h1>
<hr />

<body style="background-color: #D3D3D3"> 

@if (Model.Count() == 0)
        {
          <span> No Records Found!!!</span>
       }
        else
        {
            <div class="row">
               @foreach (var furniture in Model)
        {
            <div class="row row-cols-2 row-cols-md-2 g-4">

                <div class="card  border-dark mt-2 mr-5 text-dark" style="max-width: 520px;">
                    <div class="row g-0">
                        <div class="col-md-4">
                            @if (@furniture.CategoryName == "Chair")
                            {
                                <img src="https://www.vyomdesign.in/media/catalog/product/cache/1/image/1200x1200/9df78eab33525d08d6e5fb8d27136e95/h/i/high-back-chair---teak-wood-1_8.jpg" class="img-fluid rounded-start" alt="Hollywood Sign on The Hill"/>
                            }
                            @if (@furniture.CategoryName == "Table")
                            {
                                <img src="https://www.betterhomeindia.com/wp-content/uploads/2019/01/5-min.jpg" class="img-fluid rounded-start" alt="Hollywood Sign on The Hill"/>
                            }
                             @if (@furniture.CategoryName == "Bed")
                            {
                                <img src="https://www.decornation.in/wp-content/uploads/2020/03/solid-wood-bedroom-beds.jpg" class="img-fluid rounded-start" alt="Hollywood Sign on The Hill"/>
                            }
                             @if (@furniture.CategoryName == "Dining")
                            {
                                <img src="https://homedesignlover.com/wp-content/uploads/2016/05/6-spin_prod.jpg" class="img-fluid rounded-start" alt="Hollywood Sign on The Hill"/>
                            } 
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                 <h5 class="card-title">@furniture.ItemName</h5>
                                 <p>Category : @furniture.CategoryName</p>
                                 <p>Wood Type : @furniture.WoodType</p>
                                 <p>Description : @furniture.ItemDescription</p>
                                 <p>Price : @furniture.ItemPrice</p>
                                 <p>CreatedBy : @furniture.CreatedBy</p>
                                 <p>CreatedDate : @furniture.CreatedDate</p>
                                 <a style="width : 80px; height:40px;" class="btn btn-primary" asp-controller="Furniture" asp-action="UpdateFurniture" asp-route-id="@furniture.Id">Edit</a>
                                 <a style="width : 100px;  height:40px;" class="btn btn-danger" asp-controller="Furniture" asp-action="DeleteFurniture" asp-route-id="@furniture.Id">Delete</a>
                            </div>
                        </div>
                     </div> 
                   </div>
               
             </div>
               
             
            }
          </div>
          
    }

    </body>

Furniture-Management-MVC/Views/Furniture/UpdateFurniture.cshtml
@model UpdateFurnitureViewModel

<link href="~/css/Update.css" rel="stylesheet" />
<h1>Edit Furniture</h1>
<hr />
<body style="background-color: #D3D3D3">
<form asp-controller="Furniture" asp-action="UpdateFurniture" method="post">

    <div class="form-group">


        <label>Name</label>
        <input type="text" asp-for="ItemName" class="form-control" />
        <span asp-validation-for="ItemName" class="text-danger"></span>

    </div>
    <div class="form-group">
        <label>Category</label>
        <select class="form-control" asp-for="CategoryId" asp-items="@Model.CategoryList"></select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
    </div>
     <div class="form-group">
        <label>Wood Type</label>
        <input type="text" asp-for="WoodType" class="form-control" />
        <span asp-validation-for="WoodType" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Description</label>
        <input type="text" asp-for="ItemDescription" class="form-control" />
        <span asp-validation-for="ItemDescription" class="text-danger"></span>
    </div>
   
    <div class="form-group">
        <label>Price</label>
        <input type="number" asp-for="ItemPrice" class="form-control" />
        <span asp-validation-for="ItemPrice" class="text-danger"></span>
    </div>
    
    <button type="submit" class="btn btn-primary">Update</button>
     <a class="btn btn-primary" asp-controller="Furniture" asp-action="Index">Cancel</a>
</form>
</body>